name: Deploy To S3
on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # - name: Set up Node.js
    #   uses: actions/setup-node@v3
    #   with:
    #     node-version: 14

    # - name: Install dependencies
    #   run: yarn install

    # - name: Build React app
    #   run: yarn run build

    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-action-dev
        aws-region: us-east-1
        role-external-id: ${{ secrets.ROLE_EXTERNAL_ID }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        role-skip-session-tagging: true

    - name: Copy files to the test website with the AWS CLI
      run: |
        aws s3 sync build s3://${{ secrets.AWS_S3_BUCKET }} --exact-timestamps --delete

    - name: Clear cache of Cloudfront
      run: |
        aws cloudfront create-invalidation --distribution-id  ${{ secrets.DISTRIBUTION_ID }} --paths "/*"
